apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-150"
  name: {{ .Values.webScheduler.dagsVolumeClaim }}
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: {{ .Values.dagVolume.size }}
