{{- if .Values.webScheduler.installWebServer -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "airflow.webserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "airflow.name" . }}
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "airflow.name" . }}
      app: {{ template "airflow.name" . }}
      tier: {{ .Values.webScheduler.web.name }}
  replicas: {{ .Values.webScheduler.web.webReplicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cfgmap-airflow-cfg.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ template "airflow.name" . }}
        app: {{ template "airflow.name" . }}
        tier: {{ .Values.webScheduler.web.name }}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ .Values.webScheduler.serviceAccountName }}
      containers:
        - name: {{ template "airflow.webserver.fullname" . }}
          image: {{ .Values.webScheduler.image }}:{{ .Values.webScheduler.tag }}
          imagePullPolicy: {{ .Values.webScheduler.imagePullPolicy }}
          ports:
            - name: {{ .Values.webScheduler.web.name }}
              containerPort: 8080
          volumeMounts:
          - name: {{ .Values.webScheduler.dagsVolumeClaim }}  
            mountPath: {{ .Values.webScheduler.dagsMountPath }}
            subPath: {{ .Values.dagVolume.dagSubPath }}
            readOnly: {{ .Values.webScheduler.web.dagVolumeReadOnly }}
          - name: {{ .Values.webScheduler.airflowCfgConfigMap }}
            mountPath: {{ .Values.webScheduler.airflowCfgPath }}
            subPath: airflow.cfg
          env:
           - name: SQL_ALCHEMY_CONN
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.secrets.name }}
                 key: {{ .Values.secrets.key.sqlAlchemyConn }}
{{- if .Values.airflowCfg.core.remoteLogging }}
           - name: AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.secrets.name }}
                 key: "{{ .Values.secrets.key.gcsLogFolder }}"
{{ end }} 
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 30
          args: ["webserver"]
          resources:
{{ toYaml .Values.webScheduler.web.resources | indent 12 }}
    {{- with .Values.webScheduler.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: airflow-configmap 
          configMap:
            name: "{{ .Values.webScheduler.airflowCfgConfigMap }}-{{ .Release.Time.Seconds }}"
        - name: {{ .Values.webScheduler.dagsVolumeClaim}} 
          persistentVolumeClaim:
            claimName: {{ .Values.webScheduler.dagsVolumeClaim}} 
            readOnly: {{ .Values.webScheduler.web.dagVolumeReadOnly }}
{{- end -}}
